# Generated by Django 4.2.23 on 2025-07-21 15:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='電話番号（ハイフン含めても可）', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='メールアドレス（ユニーク）', max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], help_text="性別（'男性' または '女性'）", max_length=2)),
                ('birth_date', models.DateField(help_text='生年月日（YYYY-MM-DD）')),
                ('nickname', models.CharField(help_text='ニックネーム', max_length=50)),
                ('user_id', models.CharField(help_text='アプリ内でのユーザーID（ユニーク）', max_length=100, unique=True)),
                ('password', models.CharField(help_text='ハッシュ化済みパスワード', max_length=128)),
                ('selected_area', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='よく遊ぶ駅のリスト（複数選択可）', size=None)),
                ('match_multiple', models.BooleanField(default=False, help_text='マッチする人数（False＝ひとり、True＝みんなで）')),
                ('occupation', models.CharField(blank=True, help_text='職業（任意）', max_length=50, null=True)),
                ('university', models.CharField(blank=True, help_text='大学名（任意）', max_length=100, null=True)),
                ('blood_type', models.CharField(blank=True, help_text='血液型（例：A型、B型、O型、AB型）', max_length=3, null=True)),
                ('height', models.CharField(blank=True, help_text='身長（例：170cm）', max_length=10, null=True)),
                ('drinking', models.CharField(blank=True, help_text='お酒（例：飲まない、たまに飲む、よく飲む）', max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, help_text='煙草（例：吸わない、たまに吸う、吸う）', max_length=50, null=True)),
                ('available_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, help_text='会える日付リスト', size=None)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル一覧',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='settee_app.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='settee_app.userprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LikeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='settee_app.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_likes', to='settee_app.userprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
